linters:
  enable:
    - gofumpt
    - gofmt
    - gosimple
    - godot
    - godox
    - dupl
    - exhaustive
    - funlen
    - gocritic
    - goprintffuncname
    - ifshort
  presets:
    - unused
