version: 2

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
    - go vet
builds:
  - goos:
      - linux
      - windows
      - darwin
    ldflags:
      - -s -w -X github.com/brittonhayes/pillager/internal/commands/version.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -X main.builtBy=goreleaser
    main: "./cmd/pillager"

checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^images:"
      - "^_examples:"

scoops:
  - name: pillager
    repository:
      owner: brittonhayes
      name: pillager-scoop
    url_template: "https://github.com/brittonhayes/pillager/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    commit_author:
      name: goreleaserbot
      email: goreleaser@carlosbecker.com
    commit_msg_template: "Scoop update for {{ .ProjectName }} version {{ .Tag }}"
    description: "Pillage filesystems for sensitive information"
    license: MIT
    homepage: "https://github.com/brittonhayes/pillager"

brews:
  - name: pillager
    goarm: "6"
    repository:
      owner: brittonhayes
      name: homebrew-pillager
    url_template: "https://github.com/brittonhayes/pillager/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    commit_author:
      name: goreleaserbot
      email: goreleaser@carlosbecker.com
    homepage: "https://github.com/brittonhayes/pillager"
    description: "Pillage filesystems for sensitive information"
    license: "MIT"

aurs:
  - name: pillager-bin
    homepage: "https://github.com/brittonhayes/pillager"
    description: "Pillage filesystems for sensitive information"
    maintainers:
      - "brittonhayes <brittonhayes@users.noreply.github.com>"
    license: "MIT"
    private_key: "{{ .Env.AUR_KEY }}"
    git_url: "ssh://aur@aur.archlinux.org/pillager-bin.git"
    provides:
      - pillager
    package: |-
      # bin
      install -Dm755 "./pillager" "${pkgdir}/usr/bin/pillager"
      
      # license
      install -Dm644 "./LICENSE" "${pkgdir}/usr/share/licenses/pillager/LICENSE"
    commit_author:
      name: "brittonhayes"
      email: "brittonhayes@users.noreply.github.com"
    commit_msg_template: "Update to {{ .Tag }}"
    goamd64: v1
