version: 2

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
    - go vet
builds:
  - goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    # Exclude 32-bit architectures to avoid integer overflow issues
    # with dependencies and focus on modern systems
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w -X github.com/brittonhayes/pillager/internal/commands/version.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -X main.builtBy=goreleaser
    main: "./cmd/pillager"

checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^images:"
      - "^_examples:"

scoops:
  - name: pillager
    repository:
      owner: brittonhayes
      name: pillager-scoop
    url_template: "https://github.com/brittonhayes/pillager/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    commit_author:
      name: goreleaserbot
      email: goreleaser@carlosbecker.com
    commit_msg_template: "Scoop update for {{ .ProjectName }} version {{ .Tag }}"
    description: "Pillage filesystems for sensitive information"
    license: MIT
    homepage: "https://github.com/brittonhayes/pillager"

homebrew:
  - name: pillager
    goarm: "6"
    repository:
      owner: brittonhayes
      name: homebrew-pillager
    url_template: "https://github.com/brittonhayes/pillager/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    commit_author:
      name: goreleaserbot
      email: goreleaser@carlosbecker.com
    homepage: "https://github.com/brittonhayes/pillager"
    description: "Pillage filesystems for sensitive information"
    license: "MIT"
