name: benchmark
on:
  push:
    branches:
      - master
      - main
  pull_request:
jobs:
  benchmark:
    name: Run benchmarks
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: go get ./...
      - name: Run benchmarks
        run: go test -bench . -benchmem ./...
