name: reviewdog

on: [ pull_request ]

jobs:
  reviewdog:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v1

      - name: misspell
        uses: reviewdog/action-golangci-lint@v1
        with:
          golangci_lint_flags: "--disable-all -E misspell"
          tool_name: misspell
          level: info
